exp_name: cot_v2_50_epochs_tensorboard
description: "CoT avec plus de subgoals et max_subgoals augmenté"

# ============================================================================
# PATHS
# ============================================================================

data: /media/cedrix/Ubuntu_2To/Alfred/alfred/data/json_feat_2.1.0              # ← CORRIGÉ !
splits: /media/cedrix/Ubuntu_2To/Alfred/alfred/data/splits/oct21.json
dout: /media/cedrix/Ubuntu_2To/Alfred/alfred_experiments/experiments/{exp_name}


# Model
model: seq2seq_cot

use_cot: true
max_subgoals: 12
cot_loss_weight: 0.2

dhid: 128
demb: 100
dframe: 2500
pframe: 300

gpu: true
batch: 12
lr: 0.001
decay_epoch: 10
epoch: 50
seed: 1

action_loss_wt: 1.0
mask_loss_wt: 0.1
pm_aux_loss_wt: 0.1
subgoal_aux_loss_wt: 0.1

vis_dropout: 0.3
lang_dropout: 0.0
input_dropout: 0.0
hstate_dropout: 0.3
attn_dropout: 0.0
actor_dropout: 0.0

num_workers: 4
save_every_epoch: true
preprocess: false